language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install pipenv --upgrade
  - pipenv install --dev

script:
  - flake8 --max-line-length 120 rebase-remotes.py
  - pytest -p no:cacheprovider